"""baseline schema (store shapes)

Revision ID: 892a7e8efbba
Revises: 
Create Date: 2026-07-26 20:21:32.553163
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '892a7e8efbba'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metadata_resources',
    sa.Column('resource', sa.String(), nullable=False),
    sa.Column('local_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('resource', 'local_id')
    )
    op.create_table('requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('owner', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requests_owner'), 'requests', ['owner'], unique=False)
    op.create_table('test_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('is_sample', sa.Boolean(), nullable=False),
    sa.Column('encrypt_at_rest', sa.Boolean(), nullable=False),
    sa.Column('publishable', sa.Boolean(), nullable=False),
    sa.Column('created_on', sa.String(), nullable=True),
    sa.Column('expires_on', sa.String(), nullable=True),
    sa.Column('access_token', sa.String(), nullable=True),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('cancelled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_sessions_owner'), 'test_sessions', ['owner'], unique=False)
    op.create_table('validations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.String(), nullable=False),
    sa.Column('certify', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validations_session_id'), 'validations', ['session_id'], unique=False)
    op.create_table('vector_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_session_id', sa.Integer(), nullable=False),
    sa.Column('mode_folder', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('prompt', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('response', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('validation', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('resubmit_count', sa.Integer(), nullable=False),
    sa.Column('missing_tc_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('capabilities', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('registration', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('internal_projection', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('expected', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('show_expected', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['test_session_id'], ['test_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vector_sets_test_session_id'), 'vector_sets', ['test_session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vector_sets_test_session_id'), table_name='vector_sets')
    op.drop_table('vector_sets')
    op.drop_index(op.f('ix_validations_session_id'), table_name='validations')
    op.drop_table('validations')
    op.drop_index(op.f('ix_test_sessions_owner'), table_name='test_sessions')
    op.drop_table('test_sessions')
    op.drop_index(op.f('ix_requests_owner'), table_name='requests')
    op.drop_table('requests')
    op.drop_table('metadata_resources')
    # ### end Alembic commands ###
